apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec: 
      containers:
        - image: "gcr.io/renderproxy-247016/api@sha256:c7733ef8c95d79f5a3251eb72a7cff9aefe128169ba763eac836f4af8590da20"
          name: api
          imagePullPolicy: Always
          ports: 
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  selector: 
    app: api
  ports:
    - port: 3002
      targetPort: 3002
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.passHostHeader: "true"
    traefik.frontend.priority: "2"
spec:
  rules:
  - host: api.renderproxy.com
    http:
      paths:
      - path: /
        backend:
          serviceName: api
          servicePort: 3002