apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec: 
      containers:
        - image: "gcr.io/renderproxy-247016/proxy@sha256:a98d77ff4a03befb60a70074ba10a0bcae5ce7db4039e591e0568c35755990a5"
          name: proxy
          imagePullPolicy: Always
          ports: 
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  type: ClusterIP
  selector: 
    app: proxy
  ports:
    - port: 3000
      targetPort: 3000
          